<?php

class  Person{
    private $name;
    private $age;

    public function __construct()
    {
    }

    # SETTER
    public function setName($name){
        $this->name = $name;
    }
    public function setAge($age){
        $this->age = $age;
    }

    # GETTER
    public function getName(){
        return $this->name;
    }
    public function getAge(){
        return $this->age;
    }

}

class Student extends Person{
    private $id;
    private $name;
    private $class;

    public function __construct()
    {
        parent::__construct();
    }

    # SETTER
    public function setID($id){
        $this->id = $id;
    }
    public function setClass($class){
        $this->class = $class;
    }

    # GETTER
    public function getID(){
        return $this->id;
    }
    public function getName(){
        return parent::getName();
    }
    public function getClass(){
        return $this->class;
    }
    public function getAge()
    {
        return parent::getAge(); // TODO: Change the autogenerated stub
    }
}


$p = new Person();
$p->setName('Rasel');


$s = new Student();

$s->setName('Test');
echo $s->getName().'<br>';
$s->setAge('23');
echo $s->getAge();
